version: "3"

services: 
    krishiai-web:
        image: satyajitghana/krishiai_backend:latest
        container_name: web
        environment: 
            - SERVING_HOSTNAME=tfserving
        restart: always
        ports: 
            - "80:3000"
        networks: 
            - app-network
    
    krishiai-tfserving:
        image: satyajitghana/krishiai_model:latest
        container_name: tfserving
        restart: always
        environment: 
            - MODEL_NAME=resnet50v2
        ports:
            - "8500:8500"
            - "8501:8501"
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge
